# Generated by Django 4.2 on 2023-06-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_total_sum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
